# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 857add9ec42c4d88917b07f4504fb87033310d73c28d634f7f6060821bad2b601de4938a4088b08f85fce91054848d75305d77de004a85fee72820580adfdcf9

test:
  secret_key_base: 7cc2bad71efae33f831396fb74186463d905b27fbb449e86b865c0dad96c268c6fa0d315890afff7303e5d89ff36c33fabad5354015ad7e7a10c560a9e59a555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
